project_id = "zfjreqgrybhjwykezcta"

[functions.ai-chat]
verify_jwt = false

[functions.stock-data]
verify_jwt = false

[functions.market-news]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false
